[project]
name = "DEGAN"
version = "0.1.0"
description = "Any description"
authors = [
  { name = "Federico Simonetta", email = "22996003+00sapo@users.noreply.github.com" },
]
dependencies = [
    "tensorflow[and-cuda]>=2.12.0",
    "numpy>=1.26.3",
    "pillow>=10.2.0",
    "opencv-python>=4.9.0.80",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = { text = "MIT" }


[tool.pdm]
package-type = "application"

[tool.pdm.dev-dependencies]
dev = [
    "ipdb>=0.13.13",
]
